"""Emit a TypeScript projection of the catalogue for the frontend.

Run via: python -m app.backtest.catalogue.emitter
The output is committed to frontend/src/generated/blocks.ts.
"""
from __future__ import annotations

import json
from pathlib import Path

from app.backtest.catalogue import CATALOGUE
from app.backtest.catalogue.types import BlockSpec, ParamSpec


def _param_to_ts(p: ParamSpec) -> dict:
    out: dict = {
        "name": p.name,
        "label": p.label,
        "kind": p.kind,
        "default": p.default,
    }
    if p.min is not None:
        out["min"] = p.min
    if p.max is not None:
        out["max"] = p.max
    if p.options:
        out["options"] = list(p.options)
    return out


def _spec_to_ts_object(spec: BlockSpec) -> str:
    params_json = json.dumps([_param_to_ts(p) for p in spec.params], indent=4)
    params_indented = "\n".join("  " + line for line in params_json.splitlines())
    inputs_json = json.dumps([{"name": p.name, "label": p.label} for p in spec.inputs])
    outputs_json = json.dumps([{"name": p.name, "label": p.label, "explain": p.explain} for p in spec.outputs])
    return (
        f"  {{\n"
        f"    type: {json.dumps(spec.type)},\n"
        f"    category: {json.dumps(spec.category)},\n"
        f"    label: {json.dumps(spec.label)},\n"
        f"    inputs: {inputs_json},\n"
        f"    outputs: {outputs_json},\n"
        f"    params:\n{params_indented},\n"
        f"  }}"
    )


def emit_typescript() -> str:
    lines = [
        "// AUTO-GENERATED by backend/app/backtest/catalogue/emitter.py — DO NOT EDIT MANUALLY.",
        "// Run: cd backend && python -m app.backtest.catalogue.emitter",
        "",
        "export interface CatalogueParamSpec {",
        "  name: string;",
        "  label: string;",
        "  kind: 'int' | 'float' | 'str' | 'enum';",
        "  default: number | string;",
        "  min?: number;",
        "  max?: number;",
        "  options?: string[];",
        "}",
        "",
        "export interface CatalogueBlockSpec {",
        "  type: string;",
        "  category: 'input' | 'indicator' | 'logic' | 'signal' | 'risk';",
        "  label: string;",
        "  inputs: { name: string; label: string }[];",
        "  outputs: { name: string; label: string; explain: string }[];",
        "  params: CatalogueParamSpec[];",
        "}",
        "",
        "export const CATALOGUE_BLOCKS: CatalogueBlockSpec[] = [",
    ]

    for handler in CATALOGUE.values():
        lines.append(_spec_to_ts_object(handler.spec) + ",")

    lines += [
        "];",
        "",
        "export function getCatalogueBlock(type: string): CatalogueBlockSpec | undefined {",
        "  return CATALOGUE_BLOCKS.find((b) => b.type === type);",
        "}",
        "",
    ]

    return "\n".join(lines)


def _write_artifact() -> None:
    output = emit_typescript()
    artifact = Path(__file__).parents[4] / "frontend" / "src" / "generated" / "blocks.ts"
    artifact.parent.mkdir(parents=True, exist_ok=True)
    artifact.write_text(output)
    print(f"Written: {artifact}")


if __name__ == "__main__":
    _write_artifact()
